### ISSUE TITLE
Widgets TODO list

### ISSUE THREAD

**Issue by ghost** [UV-CDAT/VCS-widgets#2]
- [ ] Data validation
    - [ ] Legend.jsx
    - [ ] Missing.jsx (needs fixing)
    - [ ] FillareaFields.jsx
    - [x] DatawcCoordinates.jsx
    - [ ] TicsAndLabels.jsx
- [ ] Set up backend/action/reducer to stop hardcoding
    - [ ] Projection.jsx
- [ ] Usage
    - [ ] FillareaFields.jsx
- [ ] Clean up state management in GraphicsMethodEditForm
    - [ ] Move new_name logic out to EditName component
    - [ ] Move addLevel/removeLevel functions out to Levels component
- [ ] Incorporate editor components
    - [x] DatawcCoordinates
    - [ ] TicsAndLabels
    - [x] Projection
- [ ] Weirdness
    - [ ] Renaming needs to be re-worked. Saving a default boxfill copy as 'Livermore' resulted in a name of default__edit__1. Need to check my renaming logic.
    - [ ] Missing input can be a color name. Need update input/validation to reflect that.
    - [ ] xticlabels1 kinda sorta works, but needs a lot more work

**Comment by ghost** [comment]
@chaosphere2112 @mattben these are things that need working on that I came up with. do either of you have an idea more TODOs that should be on here?
